version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always
    env_file: ./key.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s
      # networks:
      # - api
 
  flask-app:
    container_name: flaskapp
    image: valento/flask:latest
    build: ./app
    restart: always
    ports:
      - "5000:5000"
    env_file: ./.env
    # environment:
    #   - DB_USERNAME=${DB_USERNAME}
    #   - DB_PASSWORD=${DB_PASSWORD}
    #   - DB_HOSTNAME=${DB_HOSTNAME}:3306
    #   - DB_NAME=${DB_NAME}
    # networks:
    #   - api
    depends_on:
      db:
        condition: service_healthy


volumes:
  db_data:
    
# networks:
#   api:
#     name: flaskapi
    
