name: CI/CD_Homework

on:
  push:
    branches:
      - master
env:
  REGISTRY: akril1k/Flask    
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:

      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: flake8 Lint
        uses: py-actions/flake8@v2